#include <Port_cfg.h>

#include <zephyr/kernel.h>
#include <zephyr/drivers/gpio.h>


// This file is autogenerated, any hand modifications will be lost!

Port_ConfigType PortConfigs = {
	.num_pins = PORT_NUM_OF_PINS,
	.pin[0] = {
		.pin_id = 4,
		.pin_dir = PORT_PIN_OUT,
		.pin_mode = PORT_PIN_MODE_LIN,
		.pin_level = PORT_PIN_LEVEL_LOW,
		.pin_initial_mode = PORT_PIN_MODE_LIN,
		.pin_dir_changeable = FALSE,
		.pin_mode_changeable = FALSE
	},
	.pin[1] = {
		.pin_id = 5,
		.pin_dir = PORT_PIN_IN,
		.pin_mode = PORT_PIN_MODE_LIN,
		.pin_level = PORT_PIN_LEVEL_LOW,
		.pin_initial_mode = PORT_PIN_MODE_LIN,
		.pin_dir_changeable = FALSE,
		.pin_mode_changeable = FALSE
	},
	.pin[2] = {
		.pin_id = 25,
		.pin_dir = PORT_PIN_OUT,
		.pin_mode = PORT_PIN_MODE_DIO,
		.pin_level = PORT_PIN_LEVEL_LOW,
		.pin_initial_mode = PORT_PIN_MODE_DIO,
		.pin_dir_changeable = FALSE,
		.pin_mode_changeable = FALSE
	},
	.pin[3] = {
		.pin_id = 0,
		.pin_dir = PORT_PIN_IN,
		.pin_mode = PORT_PIN_MODE_SPI,
		.pin_level = PORT_PIN_LEVEL_LOW,
		.pin_initial_mode = PORT_PIN_MODE_SPI,
		.pin_dir_changeable = FALSE,
		.pin_mode_changeable = FALSE
	},
	.pin[4] = {
		.pin_id = 1,
		.pin_dir = PORT_PIN_OUT,
		.pin_mode = PORT_PIN_MODE_DIO,
		.pin_level = PORT_PIN_LEVEL_HIGH,
		.pin_initial_mode = PORT_PIN_MODE_DIO,
		.pin_dir_changeable = FALSE,
		.pin_mode_changeable = FALSE
	},
	.pin[5] = {
		.pin_id = 2,
		.pin_dir = PORT_PIN_OUT,
		.pin_mode = PORT_PIN_MODE_SPI,
		.pin_level = PORT_PIN_LEVEL_LOW,
		.pin_initial_mode = PORT_PIN_MODE_SPI,
		.pin_dir_changeable = FALSE,
		.pin_mode_changeable = FALSE
	},
	.pin[6] = {
		.pin_id = 3,
		.pin_dir = PORT_PIN_OUT,
		.pin_mode = PORT_PIN_MODE_SPI,
		.pin_level = PORT_PIN_LEVEL_LOW,
		.pin_initial_mode = PORT_PIN_MODE_SPI,
		.pin_dir_changeable = FALSE,
		.pin_mode_changeable = FALSE
	},
	.pin[7] = {
		.pin_id = 16,
		.pin_dir = PORT_PIN_OUT,
		.pin_mode = PORT_PIN_MODE_DIO,
		.pin_level = PORT_PIN_LEVEL_HIGH,
		.pin_initial_mode = PORT_PIN_MODE_DIO,
		.pin_dir_changeable = FALSE,
		.pin_mode_changeable = FALSE
	},
	.pin[8] = {
		.pin_id = 17,
		.pin_dir = PORT_PIN_OUT,
		.pin_mode = PORT_PIN_MODE_DIO,
		.pin_level = PORT_PIN_LEVEL_HIGH,
		.pin_initial_mode = PORT_PIN_MODE_DIO,
		.pin_dir_changeable = FALSE,
		.pin_mode_changeable = FALSE
	},
	.pin[9] = {
		.pin_id = 18,
		.pin_dir = PORT_PIN_OUT,
		.pin_mode = PORT_PIN_MODE_DIO,
		.pin_level = PORT_PIN_LEVEL_HIGH,
		.pin_initial_mode = PORT_PIN_MODE_DIO,
		.pin_dir_changeable = FALSE,
		.pin_mode_changeable = FALSE
	},
	.pin[10] = {
		.pin_id = 19,
		.pin_dir = PORT_PIN_OUT,
		.pin_mode = PORT_PIN_MODE_DIO,
		.pin_level = PORT_PIN_LEVEL_HIGH,
		.pin_initial_mode = PORT_PIN_MODE_DIO,
		.pin_dir_changeable = FALSE,
		.pin_mode_changeable = FALSE
	},
	.pin[11] = {
		.pin_id = 20,
		.pin_dir = PORT_PIN_IN,
		.pin_mode = PORT_PIN_MODE_DIO,
		.pin_level = PORT_PIN_LEVEL_HIGH,
		.pin_initial_mode = PORT_PIN_MODE_DIO,
		.pin_dir_changeable = FALSE,
		.pin_mode_changeable = FALSE
	},
	.pin[12] = {
		.pin_id = 21,
		.pin_dir = PORT_PIN_IN,
		.pin_mode = PORT_PIN_MODE_DIO,
		.pin_level = PORT_PIN_LEVEL_HIGH,
		.pin_initial_mode = PORT_PIN_MODE_DIO,
		.pin_dir_changeable = FALSE,
		.pin_mode_changeable = FALSE
	},
	.pin[13] = {
		.pin_id = 22,
		.pin_dir = PORT_PIN_IN,
		.pin_mode = PORT_PIN_MODE_DIO,
		.pin_level = PORT_PIN_LEVEL_HIGH,
		.pin_initial_mode = PORT_PIN_MODE_DIO,
		.pin_dir_changeable = FALSE,
		.pin_mode_changeable = FALSE
	}
};

const struct gpio_dt_spec gpiopin25 = GPIO_DT_SPEC_GET(DT_PATH(zephyr_user), gpiopin25_gpios);
const struct gpio_dt_spec gpiopin01 = GPIO_DT_SPEC_GET(DT_PATH(zephyr_user), gpiopin01_gpios);
const struct gpio_dt_spec gpiopin16 = GPIO_DT_SPEC_GET(DT_PATH(zephyr_user), gpiopin16_gpios);
const struct gpio_dt_spec gpiopin17 = GPIO_DT_SPEC_GET(DT_PATH(zephyr_user), gpiopin17_gpios);
const struct gpio_dt_spec gpiopin18 = GPIO_DT_SPEC_GET(DT_PATH(zephyr_user), gpiopin18_gpios);
const struct gpio_dt_spec gpiopin19 = GPIO_DT_SPEC_GET(DT_PATH(zephyr_user), gpiopin19_gpios);
const struct gpio_dt_spec gpiopin20 = GPIO_DT_SPEC_GET(DT_PATH(zephyr_user), gpiopin20_gpios);
const struct gpio_dt_spec gpiopin21 = GPIO_DT_SPEC_GET(DT_PATH(zephyr_user), gpiopin21_gpios);
const struct gpio_dt_spec gpiopin22 = GPIO_DT_SPEC_GET(DT_PATH(zephyr_user), gpiopin22_gpios);


int port_zephyr_dt_init(void) {
	int retval = 0;

	/* check if pin 25 is configured properly in dts file */
	retval = gpio_is_ready_dt(&gpiopin25);
	if (!retval)
		return -25;

	/* configure the pin 25 for Car-OS (AUTOSAR) */
	retval = gpio_pin_configure_dt(&gpiopin25, GPIO_OUTPUT_ACTIVE);
	if (retval < 0)
		return -25;


	/* check if pin 01 is configured properly in dts file */
	retval = gpio_is_ready_dt(&gpiopin01);
	if (!retval)
		return -1;

	/* configure the pin 01 for Car-OS (AUTOSAR) */
	retval = gpio_pin_configure_dt(&gpiopin01, GPIO_OUTPUT_ACTIVE);
	if (retval < 0)
		return -1;


	/* check if pin 16 is configured properly in dts file */
	retval = gpio_is_ready_dt(&gpiopin16);
	if (!retval)
		return -16;

	/* configure the pin 16 for Car-OS (AUTOSAR) */
	retval = gpio_pin_configure_dt(&gpiopin16, GPIO_OUTPUT_ACTIVE);
	if (retval < 0)
		return -16;


	/* check if pin 17 is configured properly in dts file */
	retval = gpio_is_ready_dt(&gpiopin17);
	if (!retval)
		return -17;

	/* configure the pin 17 for Car-OS (AUTOSAR) */
	retval = gpio_pin_configure_dt(&gpiopin17, GPIO_OUTPUT_ACTIVE);
	if (retval < 0)
		return -17;


	/* check if pin 18 is configured properly in dts file */
	retval = gpio_is_ready_dt(&gpiopin18);
	if (!retval)
		return -18;

	/* configure the pin 18 for Car-OS (AUTOSAR) */
	retval = gpio_pin_configure_dt(&gpiopin18, GPIO_OUTPUT_ACTIVE);
	if (retval < 0)
		return -18;


	/* check if pin 19 is configured properly in dts file */
	retval = gpio_is_ready_dt(&gpiopin19);
	if (!retval)
		return -19;

	/* configure the pin 19 for Car-OS (AUTOSAR) */
	retval = gpio_pin_configure_dt(&gpiopin19, GPIO_OUTPUT_ACTIVE);
	if (retval < 0)
		return -19;


	/* check if pin 20 is configured properly in dts file */
	retval = gpio_is_ready_dt(&gpiopin20);
	if (!retval)
		return -20;

	/* configure the pin 20 for Car-OS (AUTOSAR) */
	retval = gpio_pin_configure_dt(&gpiopin20, GPIO_INPUT);
	if (retval < 0)
		return -20;


	/* check if pin 21 is configured properly in dts file */
	retval = gpio_is_ready_dt(&gpiopin21);
	if (!retval)
		return -21;

	/* configure the pin 21 for Car-OS (AUTOSAR) */
	retval = gpio_pin_configure_dt(&gpiopin21, GPIO_INPUT);
	if (retval < 0)
		return -21;


	/* check if pin 22 is configured properly in dts file */
	retval = gpio_is_ready_dt(&gpiopin22);
	if (!retval)
		return -22;

	/* configure the pin 22 for Car-OS (AUTOSAR) */
	retval = gpio_pin_configure_dt(&gpiopin22, GPIO_INPUT);
	if (retval < 0)
		return -22;

	return 0;
}




const struct gpio_dt_spec *port_get_zephyr_dt_spec(int port_id) {
	const struct gpio_dt_spec *dt_spec = NULL;

	if ((port_id < 0) || (port_id > MAX_PORT_ID))
		return NULL;

	switch(port_id) {
		case 25:
			dt_spec = &gpiopin25;
			break;
		case 1:
			dt_spec = &gpiopin01;
			break;
		case 16:
			dt_spec = &gpiopin16;
			break;
		case 17:
			dt_spec = &gpiopin17;
			break;
		case 18:
			dt_spec = &gpiopin18;
			break;
		case 19:
			dt_spec = &gpiopin19;
			break;
		case 20:
			dt_spec = &gpiopin20;
			break;
		case 21:
			dt_spec = &gpiopin21;
			break;
		case 22:
			dt_spec = &gpiopin22;
			break;
		default:
			break;
	}

	return dt_spec;
}

