#ifndef NAMMA_AUTOSAR_PORT_CFG_H
#define NAMMA_AUTOSAR_PORT_CFG_H

// This file is autogenerated, any hand modifications will be lost!

#include <Port_Types.h>


typedef struct {
	Port_PinType pin_id;
	Port_PinDirectionType pin_dir;
	boolean pin_dir_changeable;
	Port_PinModeType pin_mode;
	Port_PinModeType pin_initial_mode;
	uint8 pin_level;
	boolean pin_mode_changeable;
} PortPin;


#define PORT_NUM_OF_PINS  (14)
typedef struct {
	Port_PinType num_pins;
	PortPin pin[PORT_NUM_OF_PINS];
} Port_ConfigType;

extern Port_ConfigType PortConfigs;

#define MAX_PORT_ID  (25)



extern const struct gpio_dt_spec gpiopin25;
extern const struct gpio_dt_spec gpiopin01;
extern const struct gpio_dt_spec gpiopin16;
extern const struct gpio_dt_spec gpiopin17;
extern const struct gpio_dt_spec gpiopin18;
extern const struct gpio_dt_spec gpiopin19;
extern const struct gpio_dt_spec gpiopin20;
extern const struct gpio_dt_spec gpiopin21;
extern const struct gpio_dt_spec gpiopin22;

const struct gpio_dt_spec *port_get_zephyr_dt_spec(int port_id);


#endif
